<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="TestScenarioLang" nsURI="http://gemoc.org/moccml/testscenariolang"
    nsPrefix="TestScenarioLang">
  <eClassifiers xsi:type="ecore:EClass" name="MseStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="clocks" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//Clock"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fireState" upperBound="-1"
        eType="ecore:EEnum ../../fr.inria.aoste.trace/model/trace.ecore#//FiredStateKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableState" upperBound="-1"
        eType="ecore:EEnum ../../fr.inria.aoste.trace/model/trace.ecore#//EnableStateKind"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="liveState" upperBound="-1"
        eType="#//LiveStateKind"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ObjectVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" lowerBound="1" eType="ecore:EClass platform:/plugin/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="initialValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario">
    <eStructuralFeatures xsi:type="ecore:EReference" name="modelImports" upperBound="-1"
        eType="ecore:EClass ../../fr.inria.aoste.timesquare.ccslkernel.model/model/TimeModel.ecore#//ImportStatement"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//ObjectVariable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statementSequence" upperBound="-1"
        eType="#//Statement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="classImports" upperBound="-1"
        eType="#//ImportJavaStatement" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="LiveStateKind">
    <eLiterals name="isAlive"/>
    <eLiterals name="isDead" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RewritingRuleCallStatement" eSuperTypes="#//Statement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="objectVariable" lowerBound="1"
        eType="#//ObjectVariable"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="method" lowerBound="1"
        eType="ecore:EClass platform:/plugin/org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameters" upperBound="-1"
        eType="#//Variable" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Statement"/>
  <eClassifiers xsi:type="ecore:EClass" name="ImportJavaStatement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="importedNamespace" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Constant" eSuperTypes="#//Variable"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntegerLiteral" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableRef" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="var" lowerBound="1" eType="#//ObjectVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringLiteral" eSuperTypes="#//Constant">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EObjectRef" eSuperTypes="#//Variable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="object" lowerBound="1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EObject"/>
  </eClassifiers>
</ecore:EPackage>
