/*
 * generated by Xtext
 */
package org.eclipse.gemoc.execution.moccml.testscenariolang.xtext.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.gemoc.execution.moccml.testscenariolang.xtext.services.TestScenarioLangGrammarAccess;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.GroupAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;

@SuppressWarnings("all")
public abstract class AbstractTestScenarioLangSyntacticSequencer extends AbstractSyntacticSequencer {

	protected TestScenarioLangGrammarAccess grammarAccess;
	protected AbstractElementAlias match_MseStatement_SemicolonKeyword_4_q;
	protected AbstractElementAlias match_RewritingRuleCallStatement_SemicolonKeyword_3_q;
	protected AbstractElementAlias match_RewritingRuleCallStatement___LeftParenthesisKeyword_2_3_0_RightParenthesisKeyword_2_3_2__q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (TestScenarioLangGrammarAccess) access;
		match_MseStatement_SemicolonKeyword_4_q = new TokenAlias(false, true, grammarAccess.getMseStatementAccess().getSemicolonKeyword_4());
		match_RewritingRuleCallStatement_SemicolonKeyword_3_q = new TokenAlias(false, true, grammarAccess.getRewritingRuleCallStatementAccess().getSemicolonKeyword_3());
		match_RewritingRuleCallStatement___LeftParenthesisKeyword_2_3_0_RightParenthesisKeyword_2_3_2__q = new GroupAlias(false, true, new TokenAlias(false, false, grammarAccess.getRewritingRuleCallStatementAccess().getLeftParenthesisKeyword_2_3_0()), new TokenAlias(false, false, grammarAccess.getRewritingRuleCallStatementAccess().getRightParenthesisKeyword_2_3_2()));
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_MseStatement_SemicolonKeyword_4_q.equals(syntax))
				emit_MseStatement_SemicolonKeyword_4_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_RewritingRuleCallStatement_SemicolonKeyword_3_q.equals(syntax))
				emit_RewritingRuleCallStatement_SemicolonKeyword_3_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else if (match_RewritingRuleCallStatement___LeftParenthesisKeyword_2_3_0_RightParenthesisKeyword_2_3_2__q.equals(syntax))
				emit_RewritingRuleCallStatement___LeftParenthesisKeyword_2_3_0_RightParenthesisKeyword_2_3_2__q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     clocks+=[Clock|ID] (ambiguity) (rule end)
	 */
	protected void emit_MseStatement_SemicolonKeyword_4_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ';'?
	 *
	 * This ambiguous syntax occurs at:
	 *     method=[JvmOperation|ID] ('(' ')')? (ambiguity) (rule end)
	 *     parameters+=Variable ')' (ambiguity) (rule end)
	 */
	protected void emit_RewritingRuleCallStatement_SemicolonKeyword_3_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
	/**
	 * Ambiguous syntax:
	 *     ('(' ')')?
	 *
	 * This ambiguous syntax occurs at:
	 *     method=[JvmOperation|ID] (ambiguity) ';'? (rule end)
	 */
	protected void emit_RewritingRuleCallStatement___LeftParenthesisKeyword_2_3_0_RightParenthesisKeyword_2_3_2__q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
