/*
 * generated by Xtext
 */
package org.eclipse.gemoc.execution.moccml.testscenariolang.xtext.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.eclipse.gemoc.execution.moccml.testscenariolang.xtext.services.TestScenarioLangGrammarAccess;

public class TestScenarioLangParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private TestScenarioLangGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.eclipse.gemoc.execution.moccml.testscenariolang.xtext.parser.antlr.internal.InternalTestScenarioLangParser createParser(XtextTokenStream stream) {
		return new org.eclipse.gemoc.execution.moccml.testscenariolang.xtext.parser.antlr.internal.InternalTestScenarioLangParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Scenario";
	}
	
	public TestScenarioLangGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(TestScenarioLangGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
