/*
 * generated by Xtext
 */
package org.eclipse.gemoc.execution.moccml.testscenariolang.xtext;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class TestScenarioLangStandaloneSetup extends TestScenarioLangStandaloneSetupGenerated{

	public static void doSetup() {
		new TestScenarioLangStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

